SaM.SamPortal/Models/FeedModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SaM.SamPortal.Common.Entities;

namespace SaM.SamPortal.Models
{
    public class FeedModel
    {
        public List<Post> Posts { get; set; }

        public FeedModel(List<Post> posts)
        {
            Posts = posts;
        }
    }
}

SaM.SamPortal/Models/FeedPostModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SaM.SamPortal.Common.Entities;

namespace SaM.SamPortal.Models
{
    public class FeedPostModel
    {
        public Post Post;

        public FeedPostModel(Post post)
        {
            this.Post = post;
        }
    }
}

SaM.SamPortal/Models/PostModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SaM.SamPortal.Common.Entities;
using Commentary = SaM.SamPortal.Common.Entities.Commentary;
using Post = SaM.SamPortal.Common.Entities.Post;

namespace SaM.SamPortal.Models
{
    public class PostModel
    {
        public Post Post;
        public List<Commentary> Commentaries { get; set; }
        public List<LightUser> Users { get; set; }

        public PostModel(Post post, List<Commentary> commentaries, List<LightUser> users)
        {
            Post = post;
            Commentaries = commentaries;
            Users = users;
        }
    }
}

SaM.SamPortal/Controllers/FeedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SaM.SamPortal.Business;
using SaM.SamPortal.Common;
using SaM.SamPortal.Common.Entities;
using SaM.SamPortal.Common.Filters;
using SaM.SamPortal.Models;

namespace SaM.SamPortal.Controllers
{
    public class FeedController : Controller
    {
        //
        // GET: /Feed/

        public ActionResult Index()
        {
            List<Post> posts = new List<Post>();
            int rows;
            posts = new PostLogic().GetByCriteria(new PostFilter(pageSize: 20), out rows);

            UserLogic userLogic = new UserLogic();
            List<User> users = new List<User>();
            posts.ForEach(x => x.Author = userLogic.GetByCriteria(new UserFilter(id: x.UserId), out rows).FirstOrDefault().CustomNickname);

            return View(new FeedModel(posts));
        }

    }
}

SaM.SamPortal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SaM.SamPortal.Business;
using SaM.SamPortal.Common;
using SaM.SamPortal.Common.Entities;
using SaM.SamPortal.Common.Filters;
using SaM.SamPortal.Models;

namespace SaM.SamPortal.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public HomeController()
        {

        }

        public ActionResult Index()
        {
            PostModel postModel;

            UserLogic userLogic = new UserLogic();
            CommentaryLogic  commentaryLogic = new CommentaryLogic();
            PostLogic postLogic = new PostLogic();

            int rows;
            
            Post post = postLogic.GetById(28288);
            List<Commentary> comments = commentaryLogic.GetByCriteria(new CommentaryFilter(pageSize: 100000, postId: post.Id), out rows);
            List<User> users = new List<User>();
            comments.ForEach(x => users.Add(userLogic.GetByCriteria(new UserFilter(pageSize: 1000000, id: x.UserId), out rows).FirstOrDefault()));
            List<LightUser> Lightusers = users.Select(x => LightUser.ToLightUser(x)).ToList();

            postModel = new PostModel(post, comments, Lightusers);
            return View(postModel);
        }

    }
}

SaM.SamPortal/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SaM.SamPortal.Controllers
{
    public class PostController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

SaM.SamPortal/Views/Feed/Index.cshtml
@using SaM.SamPortal.Utils
@model SaM.SamPortal.Models.FeedModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
}
<head>
    <link href="~/Content/PostBodyStyle.css" rel="stylesheet" />
</head>

<body>
    <div class="feed">
        @{
            foreach (var Post in Model.Posts.OrderBy(x => x.Rating))
            {
                <div class="post">
                    <table>
                        <tr>
                            <td class="postRatingCollunm">
                                <span class="postRating">@Post.Rating</span>
                            </td>
                            <td class="postContentCollumn">
                                <div class="postHeader">
                                    <h1 class="postTitle">@Post.Title</h1>
                                    <span class="postDate">@DateTimeConverter.ToRelativeTime(Post.DateTime)</span>
                                    <span class="postDate">@Post.Author</span>
                                </div>

                                <div class="postContent">@Post.Text</div>
                            </td>
                        </tr>
                    </table>
                </div>
            }
        }
    </div>
</body>

SaM.SamPortal/Views/Home/Index.cshtml
@model SaM.SamPortal.Models.PostModel

@{
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
}
<head>
    <title>Главная страница</title>
    <link href="~/Content/SomeStyle.css" rel="stylesheet" />
</head>
<body>
    <div class="post">
        <div class="postHeader">
            <h1>@Model.Post.Title</h1>
            <span class="postRating">@Model.Post.Rating</span>
            <span class="postDate">@Model.Post.DateTime.ToUniversalTime()</span>
        </div>

        <div class="postContent">@Model.Post.Text</div>
    </div>
<div>
    @{
        foreach (var comment in Model.Commentaries.OrderBy(x => x.Rating))
        {
            <div class="comment">
                <div>
                    <strong>@Model.Users.Where(x => x.Id == comment.UserId).FirstOrDefault().CustomNickname</strong>
                </div>
                <div>@comment.DateTime.ToUniversalTime()</div>
                <div>
                    @comment.Text
                </div>
            </div>
        }
    }
</div>
</body>

SaM.SamPortal/Views/Shared/_PublicLayout.cshtml
<html>
<head>
    <title>Главная страница</title>
    <link href="~/Content/PublicLayoutStyle.css" rel="stylesheet" />
</head>
<body>

    <header class="siteHeader">
        <div id="HeaderBar">
            <ul>
                <li>
                    Горячее
                </li>
                <li>
                    <a href="@Url.Action("Index", "Feed")">Лучшее</a>
                </li>
                <li>
                    Свежее
                </li>
            </ul>
        </div>
    </header>

    <div>

    </div>

    <table id="mainTable">
        <tr>
            <td id="contentCollumn">@RenderBody()</td>
            <td id="controlCollumn">
                <hgroup class="title">
                    <h1>@ViewBag.Title.</h1>
                    <h2>Create a new account.</h2>
                </hgroup>

            </td>
        </tr>
    </table>

    <footer class="siteFooter"></footer>
</body>
</html>